import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  squareShape: {
    height: 80,
    width: 366,
    backgroundColor: 'white',
    borderRadius: 16,
    //marginTop: 15,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 10,
  },
  textShape: {
    margin: 2,
  },
  text: {
    color: 'black',
    textAlign: 'center',
    fontFamily: 'Poppins',
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: '700',
    height: 24,
    width: 182,
    //margin: 7,
  },
  textFil: {
    color: '#FFF',
    textAlign: 'center',
    fontFamily: 'Poppins',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    height: 21,
    width: 42,
    //margin: 7,
  },
  textFiltwo: {
    color: '#333333',
    textAlign: 'center',
    fontFamily: 'Poppins',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    height: 21,
    width: 104,
    //margin: 7,
  },
  textFilThree: {
    color: '#FFF',
    textAlign: 'center',
    fontFamily: 'Poppins',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    height: 21,
    width: 104,
    //margin:2,
  },
  textNames: {
    color: '#333',
    fontFamily: 'Inter',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '700',
    height: 17,
    width: 121,
  },
  textNamesTwo: {
    color: '#656565',
    fontFamily: 'Inter',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    height: 17,
    width: 97,
  },
  fotostyle: {
    borderRadius: 100,
    height: 63,
    width: 63,
    margin: 10,
  },
  icons: {
    height: 24,
    width: 24,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    flexShrink: 0,
  },
  container: {flex: 1},
  header: {
    backgroundColor: '#F5F7F8',
    justifyContent: 'flex-end',
    alignItems: 'stretch',
    flexDirection: 'column',
    height: 96,
    //width: 428,
    borderRadius: 16,
    padding: 16,
    //paddingHorizontal:10
  },
  textone: {
    color: '#333',
    textAlign: 'center',
    fontFamily: 'Poppins',
    fontSize: 20,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 24,
    //margin:15
  },
  texthree: {
    color: '#FFF',
    fontFamily: 'Poppins',
    fontSize: 14,
    fontWeight: '500',
    fontStyle: 'normal',
    //lineHeight:"normal",
    //margin:15
    //fontSize:18,
    //color:"white",
  },
  filter: {
    flex: 1,
    backgroundColor: '#333',
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  filtertwo: {
    flex: 1,
    backgroundColor: '#333',
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  main: {
    flex: 7,
    backgroundColor: '#333',
    alignItems: 'center',
  },
  fil: {
    flex: 1,
    backgroundColor: '#333',
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  buttonSearch: {
    flex: 1,
    height: 56,
    backgroundColor: '#333',
    borderRadius: 0.5,
    padding: 16,
  },
  inputStyle: {
    borderWidth: 0.5,
    borderColor: '#E8E8E9',
    backgroundColor: 'white',
    color: '#000',
    borderRadius: 100,
    marginTop: 20,
    paddingLeft: 24,
    width: 366,
    height: 56,
  },
  buttonShape: {
    //flex:1,
    width:84,
    height: 33,
    borderRadius: 100,
    borderColor: '#333333',
    borderWidth: 1,
    backgroundColor: '#333333',
    marginLeft: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonShapeFour: {
    width: 80,
    height: 33,
    borderRadius: 100,
    borderColor: '#FFF',
    borderWidth: 1,
    backgroundColor: '#FFF',
    marginLeft: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonShapeTwo: {
    width: 95,
    height: 33,
    borderRadius: 100,
    borderColor: '#FFF',
    borderWidth: 1,
    backgroundColor: '#FFF',
    marginLeft: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonShapeThree: {
    width: 95,
    height: 33,
    borderRadius: 100,
    borderColor: '#CDA100',
    borderWidth: 1,
    backgroundColor: '#CDA100',
    marginLeft: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textFiltwoF: {
    fontSize: 13,
    color: 'black',
    margin: 2,
  },
  textFilThreeF: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 13,
    margin: 7,
  },
  buttonShapeTwoF: {
    width: 90,
    height: 33,
    borderRadius: 100,
    borderColor: 'white',
    borderWidth: 1,
    backgroundColor: 'white',
    marginLeft: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonShapeThreeF: {
    width: 74,
    height: 33,
    borderRadius: 100,
    borderColor: '#CDA100',
    borderWidth: 1,
    backgroundColor: '#CDA100',
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonShapeF: {
    //flex:1,
    //width: 93,
    //height: 33,
    //borderRadius: 100,
    //borderColor: '#FFF',
    //borderWidth: 1,
    //backgroundColor: '#FFF',
    marginRight:5,
    justifyContent: "space-around",
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 12,

    width: 90,
    height: 33,
    borderRadius: 100,
    borderColor: '#FFF',
    borderWidth: 1,
    backgroundColor: '#FFF',
    marginLeft: 10,
    //justifyContent: 'center',
    //alignItems: 'center',
  },

  textFilF: {
    color: '#333333',
    textAlign: 'center',
    fontFamily: 'Poppins',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    height: 21,
    width: 104,
    //margin: 7,
  },
});

export default styles;
